#!/bin/bash

log=initialization_script.log

apt update && apt install -y ruby-full ruby-bundler build-essential
ruby -v 2>&1  | tee -a $log
bundler -v 2>&1 | tee -a $log

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
bash -c 'echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" > /etc/apt/sources.list.d/mongodb-org-3.2.list'

apt update && apt install -y mongodb-org

systemctl start mongod
systemctl enable mongod 2>&1 | tee -a $log
systemctl status mongod 2>&1 | tee -a $log

git clone -b monolith https://github.com/express42/reddit.git
cd reddit && bundle install

puma -d 2>&1 | tee -a $log

ps aux | grep puma | tee -a $log

